KBLA-13: Fix bindings for bh_notifications
2600hz/kazoo-blackhole pull request #39
Opened 2024-02-16 20:58 UTC by Navoda626

Previously, EventName is set at the end of the bindings as <<"notifications.", (Category)/binary, ".", EventName/binary>>, then there was a mismatch between kapi binding and the bh binding.

Now bh_notifications will set the binding kapi_definition:binding/1

2024-02-16 21:16 UTC, danielfinke approved these changes

2024-02-16 23:05 UTC, danielfinke commented on src/modules/bh_notifications.erl
> +    Subscribed = [kapi_definition:binding(kapi_notifications:api_definition(Evt)) || Evt <- ?LISTEN_TO],
I found a bug (that was here before your changes, but should be fixed). This should not be binding to all of `?LISTEN_TO`. Instead, it should only be the event you're binding for.

```suggestion
    Subscribed = [kapi_definition:binding(kapi_notifications:api_definition(Event))],
```

The same thing applies to `?LISTEN_TO` in `notifications_bind_options/0` below. Extra clauses checking for the wildcard (`<<"*">>`) in place of the category and event need to be added. Take a look at [bh_call:bindings/2](https://github.com/2600hz/kazoo-blackhole/blob/a9e4279f6caa8575dd2385db3e8c765df5dcf612/src/modules/bh_call.erl#L66-L88) for how it's being done there.

You can reproduce this by subscribing for just the `'notifications.sip.missed_call'` binding and then if you add extra events to `?LISTEN_TO`, like `new_user`, you'll find you get WS messages for those despite not subscribing for them.

You don't need to fix this in this PR, since it's not a regression, but could you look at it afterwards?

2024-02-19 18:43 UTC, Navoda626 commented on src/modules/bh_notifications.erl
> +    Subscribed = [kapi_definition:binding(kapi_notifications:api_definition(Evt)) || Evt <- ?LISTEN_TO],
@danielfinke Got it I tested the steps and there's an existing issue, I will work on this afterwards

2024-02-20 15:01 UTC, Navoda626 commented on src/modules/bh_notifications.erl
> +    Subscribed = [kapi_definition:binding(kapi_notifications:api_definition(Evt)) || Evt <- ?LISTEN_TO],
@danielfinke Did the fix for binding to all the events in `?LISTEN_TO`, I will work on the enhancement for checking wildcard afterwards

2024-02-20 17:07 UTC, danielfinke approved these changes

2024-02-20 17:07 UTC, danielfinke commented on src/modules/bh_notifications.erl
> +    Subscribed = [kapi_definition:binding(kapi_notifications:api_definition(Evt)) || Evt <- ?LISTEN_TO],
@Navoda626 great! 👍🏻

2024-02-20 17:42 UTC, icehess requested changes

2024-02-20 17:42 UTC, icehess commented on src/modules/bh_notifications.erl
> -    [{'restrict_to', [kz_term:to_atom(Event) || Event <- ?LISTEN_TO]}].
Why changing from listen to system configurable list of what to subscribe to subscribe everything?

2024-02-20 18:11 UTC, icehess commented on src/modules/bh_notifications.erl
> -    [{'restrict_to', [kz_term:to_atom(Event) || Event <- ?LISTEN_TO]}].
nvm, didn't notice the change was in `bindings/2`. thought it was for init_binding.

2024-02-20 18:34 UTC, merged