KBLA-14: Handling wildcard bindings for blackhole notifications
2600hz/kazoo-blackhole pull request #48
Opened 2024-10-23 11:14 UTC by Navoda626

Earlier we could only bind to notification events one by one, for example if we want to bind to the all the events `voicemail_new`, `voicemail_saved`, `voicemail_deleted`, `voicemail_full` related to voicemail category, we'd have to bind separately.
1. `binding: 'notifications.voicemail.voicemail_new'`
2. `binding: 'notifications.voicemail.voicemail_saved'`
3. `binding: 'notifications.voicemail.voicemail_deleted'`
4. `binding: 'notifications.voicemail.voicemail_full'`

Now if we want to bind to all vocemail category events we can use wildcard bindings as follows
`binding: 'notifications.voicemail.*'`

2024-10-23 17:43 UTC, jamesaimonetti requested changes

2024-10-23 17:43 UTC, jamesaimonetti commented on src/modules/bh_notifications.erl
> +    Definitions = [kapi_notifications:api_definition(Event) || Event <- Events],
Why iterate twice?

Also, you could build the set directly using lists:foldl then return sets:to_list.

something like:

```erlang
get_categories(Events) ->
  SetOfCats = lists:foldl(fun add_event_definitions/2, sets:new(), Events),
  sets:to_list(SetOfCats).

add_event_definition(Event, SetOfCats) ->
  Definitions = kapi_notifications:api_definition(Event)
  lists:foldl(fun add_definition_category/2, SetOfCats, Definitions).

add_definition_category(Definition, SetOfCats) ->
  sets:add_element(kapi_definition:category(Definition), SetOfCats).
```

Untested but should illustrate the idea

2024-10-23 17:43 UTC, jamesaimonetti commented on src/modules/bh_notifications.erl
> +    Definitions = [kapi_notifications:api_definition(Event) || Event <- Events],
You can have multiple generators and gives you a nice "trick":

```erlang
[kapi_definition:restrict_to(Definition)
  || Event <- Events,
     Definition <- [kapi_notifications:api_definition(Event)],
     kapi_definition:category(Definition) =:= Category
].
```

2024-10-23 17:43 UTC, jamesaimonetti commented
@Navoda626 also can you put more info in the description? Like what does this enable (with examples) that could not be done before.

2024-10-24 14:09 UTC, Navoda626 commented on src/modules/bh_notifications.erl
> +    Definitions = [kapi_notifications:api_definition(Event) || Event <- Events],
Got your point. Did it with slight changes to the proposed since one event has one definition

2024-10-24 14:09 UTC, Navoda626 commented on src/modules/bh_notifications.erl
> +    Definitions = [kapi_notifications:api_definition(Event) || Event <- Events],
Understood. This change has been done

2024-10-25 20:48 UTC, merged